import type { Metadata } from "next";
import { Tajawal } from "next/font/google";

import "./globals.css";

const tajawal = Tajawal({
  subsets: ["arabic", "latin"],
  display: "swap",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tajawal.className}`}>{children}</body>
    </html>
  );
}
