import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { ReactNode } from "react";

import "./globals.css";

export const metadata: Metadata = {
  title: "Arab Code Academy",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <html lang="ar" dir="rtl">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
